url: https://gernest.github.io


# Site settings
title: Geofrey Ernest
email: geofreyernest@live.com
description: "My website, my life."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Geofrey Ernest
  pic: me
  position: Go(Golang) developer
  social:
    - title: twitter
      url: https://twitter.com/gernesti
    - title: facebook
      url: https://www.facebook.com/geofrey.ernest.35
    - title: github
      url: https://github.com/gernest


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:  https://twitter.com/gernesti
  - title: facebook
    url: https://www.facebook.com/geofrey.ernest.35
  - title: github
    url: http://github.com/gernest

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty